version: "3.9"
services:
  profile_db:
    image: postgres
    networks:
      - otus
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
  profile:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - service_dir=profile
    environment:
      CONNECTION_STRING: 'postgres://postgres:example@localhost:5432/postgres?sslmode=disable'
      PORT: 1323
    networks:
      - otus
    ports:
      - '1323:1323'
    depends_on:
      - profile_db
networks:
  otus:
  