version: "3.9"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
      - '33060:33060'
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      CONNECTION_STRING: 'root:example@tcp(db:3306)/?multiStatements=true&timeout=5s'
      PORT: 1323
    ports:
      - '1323:1323'
    depends_on:
      - db

