version: "3.9"
services:
  db:
    image: mysql
    networks:
      - otus
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
      - '33060:33060'

networks:
  otus:
  #$ docker run -v {{ migration dir }}:/migrations --network host migrate/migrate -path=/migrations/ -database postgres://localhost:5432/database up 2