version: "3.9"
services:
  profile_db:
    image: mysql
    networks:
      - otus
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
      - '33060:33060'
  profile:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - service_dir=profile
    environment:
      CONNECTION_STRING: 'root:example@tcp(profile_db:3306)/?multiStatements=true&timeout=5s'
      PORT: 1323
    networks:
      - otus
    ports:
      - '1323:1323'
    depends_on:
      - profile_db
networks:
  otus:
  