version: "3.9"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
      - 33060:33060

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      CONNECTION_STRING: "root:example@tcp(db:3306)/?multiStatements=true"
      API_PORT: 1323
    ports:
      - "1323:1323"
    depends_on:
      - db